/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.ConexaoBD;
import classes.Pessoa;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luiza
 */
public class JFramePessoa extends javax.swing.JFrame {
    
    Connection conn;
    /**
     * Creates new form JFramePessoa
     */
    public JFramePessoa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        nomeLbl = new javax.swing.JLabel();
        cpfLbl = new javax.swing.JLabel();
        rgLbl = new javax.swing.JLabel();
        sexoLbl = new javax.swing.JLabel();
        dataNascLbl = new javax.swing.JLabel();
        grauAcadLbl = new javax.swing.JLabel();
        instituicaoLbl = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        cpfTxt = new javax.swing.JTextField();
        rgTxt = new javax.swing.JTextField();
        sexoTxt = new javax.swing.JTextField();
        dataNascTxt = new javax.swing.JTextField();
        grauAcadTxt = new javax.swing.JTextField();
        instituicaoTxt = new javax.swing.JTextField();
        voltarBtn = new javax.swing.JButton();
        cadastrarBtn = new javax.swing.JButton();
        avaliadorBtn = new javax.swing.JRadioButton();
        pesquisadorBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeLbl.setText("Nome:");

        cpfLbl.setText("CPF:");

        rgLbl.setText("RG:");

        sexoLbl.setText("Sexo:");

        dataNascLbl.setText("Data Nasc.:");

        grauAcadLbl.setText("Grau Academico:");

        instituicaoLbl.setText("Instituição:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, nomeLbl, org.jdesktop.beansbinding.ObjectProperty.create(), nomeTxt, org.jdesktop.beansbinding.BeanProperty.create("text"), "nomeTxt");
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cpfLbl, org.jdesktop.beansbinding.ObjectProperty.create(), cpfTxt, org.jdesktop.beansbinding.BeanProperty.create("text"), "cpfTxt");
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rgLbl, org.jdesktop.beansbinding.ObjectProperty.create(), rgTxt, org.jdesktop.beansbinding.BeanProperty.create("text"), "rgTxt");
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sexoLbl, org.jdesktop.beansbinding.ObjectProperty.create(), sexoTxt, org.jdesktop.beansbinding.BeanProperty.create("text"), "sexoTxt");
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, grauAcadLbl, org.jdesktop.beansbinding.ObjectProperty.create(), dataNascTxt, org.jdesktop.beansbinding.BeanProperty.create("text"), "dataTxt");
        bindingGroup.addBinding(binding);

        dataNascTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascTxtActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, grauAcadLbl, org.jdesktop.beansbinding.ObjectProperty.create(), grauAcadTxt, org.jdesktop.beansbinding.BeanProperty.create("text"), "grauAcadText");
        bindingGroup.addBinding(binding);

        grauAcadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grauAcadTxtActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, instituicaoLbl, org.jdesktop.beansbinding.ObjectProperty.create(), instituicaoTxt, org.jdesktop.beansbinding.BeanProperty.create("text"), "instituicaoTxt");
        bindingGroup.addBinding(binding);

        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        avaliadorBtn.setText("Avaliador");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pesquisadorBtn, org.jdesktop.beansbinding.ELProperty.create("${selected}"), avaliadorBtn, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        pesquisadorBtn.setText("Pesquisador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarBtn)
                .addGap(66, 66, 66)
                .addComponent(cadastrarBtn)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(avaliadorBtn)
                .addGap(40, 40, 40)
                .addComponent(pesquisadorBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLbl)
                    .addComponent(instituicaoLbl)
                    .addComponent(grauAcadLbl)
                    .addComponent(dataNascLbl)
                    .addComponent(sexoLbl)
                    .addComponent(rgLbl)
                    .addComponent(cpfLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeTxt)
                    .addComponent(cpfTxt)
                    .addComponent(rgTxt)
                    .addComponent(sexoTxt)
                    .addComponent(dataNascTxt)
                    .addComponent(grauAcadTxt)
                    .addComponent(instituicaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avaliadorBtn)
                    .addComponent(pesquisadorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLbl)
                    .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLbl)
                    .addComponent(cpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgLbl)
                    .addComponent(rgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLbl)
                    .addComponent(sexoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascLbl)
                    .addComponent(dataNascTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grauAcadLbl)
                    .addComponent(grauAcadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instituicaoLbl)
                    .addComponent(instituicaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarBtn)
                    .addComponent(cadastrarBtn))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataNascTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascTxtActionPerformed

    private void grauAcadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grauAcadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grauAcadTxtActionPerformed

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        ConexaoBD bd = new ConexaoBD();
        try {
           conn = bd.conectar();
        } catch (SQLException ex) {
            Logger.getLogger(JFramePessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (pesquisadorBtn.isSelected()){
            Pessoa pesquisador = new Pessoa();
            pesquisador.setNome(nomeTxt.getText());
            pesquisador.setCpf(cpfTxt.getText());
            pesquisador.setRg(rgTxt.getText());
            pesquisador.setSexo(sexoTxt.getText());
            pesquisador.setDataDeNascimento(dataNascTxt.getText());
            pesquisador.setGrauAcademico(grauAcadTxt.getText());
            pesquisador.setInstituicao(instituicaoTxt.getText());
            pesquisador.incluirPesquisador(conn);
        }
        else{
            Pessoa avaliador = new Pessoa();
            avaliador.setNome(nomeTxt.getText());
            avaliador.setCpf(cpfTxt.getText());
            avaliador.setRg(rgTxt.getText());
            avaliador.setSexo(sexoTxt.getText());
            avaliador.setDataDeNascimento(dataNascTxt.getText());
            avaliador.setGrauAcademico(grauAcadTxt.getText());
            avaliador.setInstituicao(instituicaoTxt.getText());
            avaliador.incluirAvaliador(conn);
        }
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton avaliadorBtn;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JLabel cpfLbl;
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JLabel dataNascLbl;
    private javax.swing.JTextField dataNascTxt;
    private javax.swing.JLabel grauAcadLbl;
    private javax.swing.JTextField grauAcadTxt;
    private javax.swing.JLabel instituicaoLbl;
    private javax.swing.JTextField instituicaoTxt;
    private javax.swing.JLabel nomeLbl;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JRadioButton pesquisadorBtn;
    private javax.swing.JLabel rgLbl;
    private javax.swing.JTextField rgTxt;
    private javax.swing.JLabel sexoLbl;
    private javax.swing.JTextField sexoTxt;
    private javax.swing.JButton voltarBtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
